kind: Service
apiVersion: v1
metadata:
  name: latch-poc-service
spec:
  selector:
    app: latch-poc-deployment
  ports:
  - protocol: TCP
    name: java-port
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: go-port
    port: 8081
    targetPort: 8081
  type: NodePort